version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: TCC-Postgres
    environment:
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ENV_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./dados:/var/lib/postgresql/data
